version: '3.9'

services:
  api-request:
    container_name: api-request
    hostname: api-request
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        USERNAME: ${USERNAME}
        GID: ${GID}
        GROUPNAME: ${GROUPNAME}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        FTP_PROXY: ${FTP_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${HTTP_PROXY:-}
        https_proxy: ${HTTPS_PROXY:-}
        ftp_proxy: ${FTP_PROXY:-}
        no_proxy: ${NO_PROXY:-}
    environment:
      HTPP_PROXY: ${HTPP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      FTP_PROXY: ${FTP_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      http_proxy: ${HTTP_PROXY:-}
      https_proxy: ${HTTPS_PROXY:-}
      ftp_proxy: ${FTP_PROXY:-}
      no_proxy: ${NO_PROXY:-}
    ports:
      - ${API_LLM_PORT}:8000
    user: ${USERNAME}
    working_dir: /api
    volumes:
      - ./api:/api
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'
  vote-system-ui:
    container_name: vote-system-ui
    hostname: vote-system-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        USERNAME: ${USERNAME}
        GID: ${GID}
        GROUPNAME: ${GROUPNAME}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        FTP_PROXY: ${FTP_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${HTTP_PROXY:-}
        https_proxy: ${HTTPS_PROXY:-}
        ftp_proxy: ${FTP_PROXY:-}
        no_proxy: ${NO_PROXY:-}
    environment:
      HTPP_PROXY: ${HTPP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      FTP_PROXY: ${FTP_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      http_proxy: ${HTTP_PROXY:-}
      https_proxy: ${HTTPS_PROXY:-}
      ftp_proxy: ${FTP_PROXY:-}
      no_proxy: ${NO_PROXY:-}
    ports:
      - ${API_LLM_PORT}:8000
    user: ${USERNAME}
    working_dir: /teramatsu/ui
    volumes:
      - ./:/teramatsu/ui
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'